import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import Sidebar from '@/components/dashboard/Sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/dashboard/app-sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center w-full min-h-screen">
          <div className="flex w-full max-w-[1440px] min-w-[320px]">
            {/* <Sidebar />
            <main className="flex-1 py-8 px-10 bg-white">{children}</main> */}
            <SidebarProvider>
              <AppSidebar />
              <main className="flex flex-col flex-1">
                <SidebarTrigger />
                <div className="py-8 px-10  bg-white">{children}</div>
              </main>
            </SidebarProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
