import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/dashboard/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center w-full bg-gray-500 min-h-screen">
          <div className="flex w-full max-w-[1440px] min-w-[320px]">
            <Sidebar />
            <main className="flex-1 py-8 px-10 bg-white">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
